---
title: "AdvancedRIntro"
author: "phil"
date: "2019<eb>뀈 2<ec>썡 24<ec>씪"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 들어가며

 이건 Hadley Wickham 이 쓴 Advanced R을 읽고 이해한 것을 본인의 언어로 풀어낸 세션입니다.
나중에 내가 다시 읽어보았을 때에도 최대한 이해가 잘 되게끔, 그리고 혹시나 다른 사람들이 참고할 경우에도 이해를 도울 수 있게끔 썼습니다. 그렇기 때문에 용어의 정리도 잘 안 되어 있을 수 있고, 단어에 대한 일관적인 번역이 안 되어 있을 수도 있습니다.
충실하게 번역을 하지 않았을 수도 있습니다. 하지만 저자가 전달하고자 하는 내용을 잘 전달하도록 노력했습니다. 영어와 한국어 혼용하여 쓸 것이고 구어체가 많이 들어갈 수도 있습니다.
또한 저는 컴퓨터관련학과가 아닌 응용통계학과를 졸업해서, 프로그래밍에 대해 깊게 알지 못합니다. 통계학과에서 R을 꽤 많이 쓰고, 좀 안다 싶었는데, 일반적인 함수를 짜는 과정에 있어 좀 더 알 필요를 느끼고 검색을 하던 중 이 책에 대해 알게 되어 이 작업을 시작하게 되었습니다.

 제이펍이라는 출판사에서 정우준 박사가 이 책을 번역해서 출판했습니다. [Advanced R 번역본](http://item.gmarket.co.kr/Item?goodscode=1371028995&pos_shop_cd=SH&pos_class_cd=111111111&pos_class_kind=T&keyword_order=advanced+r&keyword_seqno=18288091601&search_keyword=advanced+r) 하지만 본인은 이 책을 전혀 참고하지 않고 이 블로그를 쓴다는 것을 알립니다. 필요하신 분들은 이 책을 참고하시기 바랍니다. 
 
 학부 꼬꼬마 시절에는 R-cookbook이나 R Graphics Cookbook 번역서 다 구매했는데, 그런 식의 접근으로는 한계를 느껴서...
 
 This section is about "Advanced R" written by Hadley Wickham. This is some kind of repository. Notice me if there is any problem regarding copyright.
